language: java

services:
  - docker

before_install:
  - docker build . -t bozzo1337/devops-project

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)